### ISSUE TITLE
Duplicated execution of a command

### ISSUE THREAD

**Issue by Janbk** [open-cli-tools/concurrently#421]
Description: concurrently executes the first of two command twice
Expected Behavior:Both commands are executed
Environment:
* Gitlab Runner / CI
* Using Docker executor with image mcr.microsoft.com/playwright:v1.32.1-focal
* corepack prepare pnpm@8.3.1 --activate 
Reproduction: Locally (in a Docker container) not reproducible

Hi,
I am using concurrently as it is described  by [Storybook](https://storybook.js.org/docs/angular/writing-tests/test-runner#run-against-non-deployed-storybooks) to run a test runner against a locally running web-server. The web server is started with `pnpm dlx http-server...`. The test runner is at first waiting for the web server with `pnpm dlx wait-on --timeout 300000 tcp:6006 && pnpm test-storybook ...`.

_Concurrently_ starts two web server. 

See the full log of the ci runner:
[ci-runner.log](https://github.com/open-cli-tools/concurrently/files/11319152/ci-runner.log)

Can anyone see what is wrong here or what application behaves unexpected and how to make it work?

Thank you very much for the support
Kind regards
Jan

**Comment by paescuj** [comment]
Can you share the whole config?

**Comment by Janbk** [comment]
Yes, but what is configured? concurrently is called in Gitlab CI script inside a docker container.
Any idea what else is configured? Perhaps that is part of my blind spot where something is wrong but I did not take it into account.

The `.gitlab-ci.yml` is this:

```yaml
stages:
    - test

test-storybook:
    before_script:
    - echo "Configure PNPM"
    - corepack enable
    - corepack prepare pnpm@latest-8 --activate
    - pnpm config set store-dir /cache/.pnpm-store
    - echo "Install dependencies"
    - pnpm install # install dependencies
    - echo "Install GIT LFS"
    - apt-get update
    - apt-get install -y git-lfs
    - echo "Build Storybook"
    - pnpm build:storybook --quiet -o public
    - git checkout public/mockServiceWorker.js public/favicon.ico public/imgs/logo_text.svg
    image: mcr.microsoft.com/playwright:v1.32.1-focal
    stage: test
    script:
        - echo "Run storybook testing"
        - pnpm dlx concurrently -k -s first -n "SB,TEST" -c "magenta,blue" "pnpm dlx http-server public -a 127.0.0.1 --port 6006" "pnpm dlx wait-on --timeout 300000 tcp:6006 && pnpm test-storybook --browsers chromium --junit"
    needs:
        - lint
    only:
        refs:
            - manual
            - merge_requests
    artifacts:
        when: always
        reports:
            junit:
                - junit.xml

```
